### ISSUE TITLE
Add simple Chunk occlusion culling

### ISSUE THREAD

**Issue by emezeske** [emezeske/digbuild#21]

**Comment by blak3mill3r** [comment]
Currently renders the 32 closest chunks to initialize depth buffer, then does 1 occlusion query for every remaining chunk in the frustum, achieved close to 100% increase in peak fps on my box, of course when the camera is flying around in the sky there's a performance hit from the occlusion queries, looked like maybe ~30% on mine, this first draft blocks on the queries (doing nothing at all).

I didn't play with these defines at all, they may be far from optimal:

MAJOR_OCCLUDER_CHUNK_COUNT 32  (number to draw before starting occlusion queries)
MAX_OCCLUSION_QUERIES 8192    (nasty caveat, current implementation will simply not draw more potentially-occluded chunks than this, needs fixing eventually)
SAMPLES_NOT_OCCLUDED_THRESHOLD 0   (number of pixels of the chunk AABB that can be in front of the depth buffer and the chunk still not be drawn)

So there are 2 things well wrong with this implementation as of 4cefb19d20dfa25287a07fbbe3c325fb27935815:
  it will never draw more than 8192 chunks...
  it blocks on the queries
    \* I measured the time waiting on the queries with SDL_GetTicks and it was 0ms... but some CPU work could be done

Anyway I'm closing this issue because it is "simple" occlusion culling. I don't really understand why there's such a performance hit when very little is saved by occlusion ... it seems to be more costly than I expected ... Evan you should review my work I may have done something retarded, and let me know how it performs on yours
